@echo off
echo Starting Docker Compose services (PostgreSQL)...
docker compose up -d

echo Checking backend dependencies...
cd backend
if not exist node_modules (
    echo node_modules folder is missing in backend. Installing...
    call npm install
)
echo Starting NestJS backend server in a new window...
start "NestJS Backend" npm run start:dev

echo Checking frontend dependencies...
cd ..\frontend
if not exist node_modules (
    echo node_modules folder is missing in frontend. Installing...
    call npm install
)
echo Starting Next.js frontend server in a new window...
start "Next.js Frontend" npm run dev

cd ..
